name: Check for dead links

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  verify-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      - name: Verify links
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=AM | grep "\.md$" | grep -v -E "_sidebar.md" | xargs -n1  markdown-link-check -q -c .github/markdown-link-check-config.json
